// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOrv0Bi0cseqWCPSSQzYUMPUS8AQcDOOM',
    appId: '1:545391577654:web:69e50327962ddc02baa697',
    messagingSenderId: '545391577654',
    projectId: 'ways-a-travel-partner',
    authDomain: 'ways-a-travel-partner.firebaseapp.com',
    databaseURL: 'https://ways-a-travel-partner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ways-a-travel-partner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgdnTpGvAAPhgy2VGxLCyy1-oTTSDv-k',
    appId: '1:545391577654:android:60319315bc47202fbaa697',
    messagingSenderId: '545391577654',
    projectId: 'ways-a-travel-partner',
    databaseURL: 'https://ways-a-travel-partner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ways-a-travel-partner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pPkpQ4B7TwLDJxk5siD4JS7tcsbZHW0',
    appId: '1:545391577654:ios:3709bf5c8f97a500baa697',
    messagingSenderId: '545391577654',
    projectId: 'ways-a-travel-partner',
    databaseURL: 'https://ways-a-travel-partner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ways-a-travel-partner.appspot.com',
    iosBundleId: 'com.example.wayes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0pPkpQ4B7TwLDJxk5siD4JS7tcsbZHW0',
    appId: '1:545391577654:ios:aef861eeae41c438baa697',
    messagingSenderId: '545391577654',
    projectId: 'ways-a-travel-partner',
    databaseURL: 'https://ways-a-travel-partner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ways-a-travel-partner.appspot.com',
    iosBundleId: 'com.example.wayes.RunnerTests',
  );
}
